# configuration for https://github.com/caksoylar/keymap-drawer
parse_config:
  raw_binding_map:
    # custom
    "&swapper": Next Win
    "&kp LS(TAB)": Prev Win
    "&dot_spc": Sentence
    "&num_dance": { "t": "Numword", "s": "Sticky Num" }
    "&magic_shift": { "t": Magic, "h": "Shift" }
    "&smart_mouse": Smart Mouse
    "&undo_redo": { "t": Undo, "h": "Redo" }

    # rgb
    '&rgb_ug RGB_TOG':
      tap: $$mdi:toggle-switch$$
      hold: $$mdi:led-on$$
      shifted: $$mdi:led-outline$$
      type: toggle
    '&rgb_ug RGB_BRI':
      tap:     $$mdi:led-on$$
      shifted: $$mdi:white-balance-sunny$$
      type:    sym_by_sym
    '&rgb_ug RGB_SAI':
      tap:     $$mdi:led-on$$
      shifted: $$mdi:eyedropper$$
      type:    sym_by_sym
    '&rgb_ug RGB_HUI':
      tap:     $$mdi:led-on$$
      shifted: $$mdi:palette$$
      type:    sym_by_sym
    '&rgb_ug RGB_BRD':
      tap:     $$mdi:led-outline$$
      shifted: $$mdi:white-balance-sunny$$
      type:    sym_by_sym
    '&rgb_ug RGB_SAD':
      tap:     $$mdi:led-outline$$
      shifted: $$mdi:eyedropper$$
      type:    sym_by_sym
    '&rgb_ug RGB_HUD':
      tap:     $$mdi:led-outline$$
      shifted: $$mdi:palette$$
      type:    sym_by_sym
    '&rgb_ug RGB_COLOR_HSB(25,100,0)':
      tap:     $$mdi:led-on$$
      shifted: $$mdi:gradient-horizontal$$
      hold:    "(25,100,0)"
      type:    sym_by_sym
    '&rgb_ug RGB_COLOR_HSB(25,100,80)':
      tap:     $$mdi:led-on$$
      shifted: $$mdi:gradient-horizontal$$
      hold:    "(25,100,80)"
      type:    sym_by_sym
    '&rgb_ug RGB_COLOR_HSB(25,0,100)':
      tap:     $$mdi:led-on$$
      shifted: $$mdi:gradient-horizontal$$
      hold:    "(25,0,100)"
      type:    sym_by_sym

    # Home rows
    "&hml LCTL S":
      tap: 'S'
      shifted: $$mdi:apple-keyboard-control$$
    "&hml LALT D":
      tap: 'D'
      shifted: $$mdi:apple-keyboard-option$$
    "&hml LGUI F":
      tap: 'F'
      shifted: $$mdi:apple-keyboard-command$$
    "&hmr LGUI J":
      tap: 'J'
      shifted: $$mdi:apple-keyboard-comman$$
    "&hmr LALT K":
      tap: 'K'
      shifted: $$mdi:apple-keyboard-option$$
    "&hmr LCTL L":
      tap: 'L'
      shifted: $$mdi:apple-keyboard-control$$
    
    # Modifiers
    "&caps_word": $$mdi:alpha-w-box$$
    "&esc_grave":
      tap: $$mdi:keyboard-esc$$
      shifted: $$tabler:world$$

    # Empty
    "&none":
      tap: $$mdi:minus-circle-outline$$
      type: none

    # Whitespace
    "&bkspc_del":
      type: backspace
      tap: $$mdi:backspace$$
      shifted: $$mdi:backspace-reverse-outline$$

    # Mouse
    "&msc SCRL_UP":
      tap: $$mdi:pan-up$$
      hold: ''
      shifted: ''
    "&msc SCRL_DOWN":
      tap: $$mdi:pan-down$$
      hold: ''
      shifted: ''
    "&msc SCRL_LEFT":
      tap: $$mdi:pan-left$$
      hold: ''
      shifted: ''
    "&msc SCRL_RIGHT":
      tap: $$mdi:pan-right$$
      hold: ''
      shifted: ''
    "&mmv MOVE_LEFT":
      tap: $$mdi:menu-left$$
      hold: ''
      shifted: $$mdi:mouse$$
    "&mmv MOVE_RIGHT":
      tap: $$mdi:menu-right$$
      hold: ''
      shifted: $$mdi:mouse$$
    "&mmv MOVE_UP":
      tap: $$mdi:menu-up$$
      hold: ''
      shifted: $$mdi:mouse$$
    "&mmv MOVE_DOWN":
      tap: $$mdi:menu-down$$
      hold: ''
      shifted: $$mdi:mouse$$
    "&mkp LCLK":
      tap: $$mdi:mouse-left-click-outline$$
    "&mkp RCLK":
      tap: $$mdi:mouse-right-click-outline$$
    "&mkp MCLK":
      tap: $$mdi:mouse-scroll-wheel$$

    # Bluetooth
    "&bt BT_SEL 0":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 1
    "&bt BT_SEL 1":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 2
    "&bt BT_SEL 2":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 3
    "&bt BT_SEL 3":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 4
    "&bt BT_SEL 4":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 5
    "&out OUT_TOG":
      shifted: $$mdi:usb$$
      tap: $$mdi:toggle-switch$$
      hold: $$mdi:bluetooth$$
    "&bt BT_PRV":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: $$mdi:arrow-up-bold$$
    "&bt BT_NXT":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: $$mdi:arrow-down-bold$$
    # Reset
    "&sys_reset":
      type: bootloader
      tap: $$mdi:backup-restore$$
    "&bootloader":
      tap: $$mdi:progress-download$$

    # systems
    '&out OUT_BLE':
      tap: $$mdi:keyboard$$
      shifted: $$mdi:bluetooth$$
      type: sym_by_sym
    '&out OUT_USB':
      tap: $$mdi:keyboard$$
      shifted: $$mdi:usb$$
      type: sym_by_sym
    '&out OUT_TOG':
      tap: $$mdi:toggle-switch$$
      hold: $$mdi:bluetooth$$
      shifted: $$mdi:usb$$
      type: toggle

  zmk_combos:
    combo_lbkt:
      key:
        shifted: "{"
        hold: "["
    combo_rbkt:
      key:
        shifted: "}"
        hold: "]"
    combo_semicolon:
      key:
        shifted: ":"
        hold: ";"

  zmk_keycode_map:
    # custom mappings

    LG: $$mdi:apple-keyboard-command$$
    LGUI: $$mdi:apple-keyboard-command$$
    LEFT_GUI: $$mdi:apple-keyboard-command$$
    RG: $$mdi:apple-keyboard-command$$
    RGUI: $$mdi:apple-keyboard-command$$
    RIGHT_GUI: $$mdi:apple-keyboard-command$$
    LA: $$mdi:apple-keyboard-option$$
    LALT: $$mdi:apple-keyboard-option$$
    LEFT_ALT: $$mdi:apple-keyboard-option$$
    RA: $$mdi:apple-keyboard-option$$
    RALT: $$mdi:apple-keyboard-option$$
    RIGHT_ALT: $$mdi:apple-keyboard-option$$
    LS: $$mdi:apple-keyboard-shift$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LEFT_SHIFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RIGHT_SHIFT: $$mdi:apple-keyboard-shift$$
    RS: $$mdi:apple-keyboard-shift$$
    RC: $$mdi:apple-keyboard-control$$
    RCTRL: $$mdi:apple-keyboard-control$$
    RIGHT_CONTROL: $$mdi:apple-keyboard-control$$
    LC: $$mdi:apple-keyboard-control$$
    LCTRL: $$mdi:apple-keyboard-control$$
    LEFT_CONTROL: $$mdi:apple-keyboard-control$$

    # Sound
    C_MUTE: $$mdi:volume-off$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-low$$
    C_VOLUME_UP: $$mdi:volume-high$$
    C_VOLUME_DOWN: $$mdi:volume-low$$

    # Media
    C_NEXT: $$mdi:skip-next$$
    C_PREV: $$mdi:skip-previous$$
    C_PP: $$mdi:play-pause$$

    # Bluetooth
    BT_CLR: $$mdi:bluetooth-off$$
    BT_SEL: $$mdi:bluetooth-connect$$

    # Settings
    C_BRI_UP: $$mdi:brightness-5$$
    C_BRIGHTNESS_INC: $$mdi:brightness-5$$
    C_BRI_DN: $$mdi:brightness-7$$
    C_BRI_DEC: $$mdi:brightness-7$$
    C_BRIGHTNESS_DEC: $$mdi:brightness-7$$

    # System
    C_POWER: $$mdi:power-standby$$
    C_AL_LOCK: $$mdi:lock$$
    K_CANCEL: $$mdi:close-box$$
    K_FIND: $$mdi:apple-finder$$

    ESC: Esc
    SPACE: ␣
    BACKSPACE: ⌫
    BSPC: ⌫
    RET: ⏎
    TAB: ↹
    PG_UP: Page ↑
    PG_DN: Page ↓
    INS: Insert
    HOME: Home
    END: End
    CAPS: Caps Lock
    PSCRN: Print Scrn
    PAUSE_BREAK: Pause Break
    GLOBE: $$tabler:world$$

    UP: ↑
    DOWN: ↓
    LEFT: ←
    RIGHT: →

    C_PP: ⏯
    C_NEXT: ⏭️
    C_PREV: ⏮️

    LG(TAB): Tab →
    LG(LS(TAB)): Tab ←
    LG(W): Win Close
    LG(C): Copy
    LG(X): Cut
    LG(Z): Undo
    LG(LS(Z)): Redo
    LG(A): Select All
    LG(L): Lock

    CAPSLOCK: $$mdi:apple-keyboard-caps$$
    CAPS: $$mdi:apple-keyboard-caps$$

    # Numbers
    N1:
      tap: 1
      shifted: "!"
    N2:
      tap: 2
      shifted: "@"
    N3:
      tap: 3
      shifted: "#"
    N4:
      tap: 4
      shifted: "$"
    N5:
      tap: 5
      shifted: "%"
    N6:
      tap: 6
      shifted: "^"
    N7:
      tap: 7
      shifted: "&"
    N8:
      tap: 8
      shifted: "*"
    N9:
      tap: 9
      shifted: "("
    N0:
      tap: 0
      shifted: ")"

    # defaults
    AMPERSAND: '&'
    AMPS: '&'
    APOS: "'"
    APOSTROPHE: "'"
    ASTERISK: '*'
    ASTRK: '*'
    AT: '@'
    AT_SIGN: '@'
    BSLH: \
    CARET: ^
    COLON: ':'
    COMMA: ','
    DLLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: '='
    EXCL: '!'
    EXCLAMATION: '!'
    FSLH: /
    GRAVE: '`'
    GREATER_THAN: '>'
    GT: '>'
    HASH: '#'
    LBKT: '['
    LBRC: '{'
    LEFT_BRACE: '{'
    LEFT_BRACKET: '['
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: '-'
    NON_US_BACKSLASH: \
    NON_US_BSLH: '|'
    NON_US_HASH: '#'
    NUHS: '#'
    PERCENT: '%'
    PERIOD: .
    PIPE: '|'
    PIPE2: '|'
    PLUS: +
    POUND: '#'
    PRCNT: '%'
    QMARK: '?'
    QUESTION: '?'
    RBKT: ']'
    RBRC: '}'
    RIGHT_BRACE: '}'
    RIGHT_BRACKET: ']'
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: ;
    SEMICOLON: ;
    SINGLE_QUOTE: ''''
    SLASH: /
    SQT: ''''
    STAR: '*'
    TILDE: '~'
    TILDE2: '~'
    UNDER: _
    UNDERSCORE: _
draw_config:
  footer_text: 'Created with <a href="https://github.com/caksoylar/keymap-drawer">keymap-drawer</a>'
  dark_mode: auto